export const anime = [
  {
    id: 1,
    title: "Demon Slayer Swordsmith Village Arc",
    slug: "demon-slayer-s3",
    sub_ep: "11",
    dub_ep: "6",
    total_ep: "11",
    categories: ["2023", "r", "sub", "dub", "tv"],
    description: "Swordsmith Village Arc of Kimetsu no Yaiba.",
    thumbnail: require("../assets/images/demon_slayer/DemonSlayer_Season3_Poster.jpg"),
  },
  {
    id: 2,
    title: "KamiKatsu: Working for God in a Godless World",
    slug: "kamikatsu",
    sub_ep: "11",
    dub_ep: "10",
    total_ep: "12",
    categories: ["2023", "sub", "dub", "tv"],
    description:
      "Yukito's parents are the leaders of a cult. After he gets sacrificed, he gets reincarnated into another world where religion doesn't exist and porn books are akin to a child's doodles. He finds that it's also a world where your life and death is decided by the country. While obstructing his friend's execution, both of them lose their lives. Just at that moment, the god of his religion comes to their world and revives them.",
    thumbnail: require("../assets/images/kamikatsu/kamikatsu_full.avif"),
  },
  {
    id: 3,
    title: "Why Raeliana Ended Up at the Duke's Mansion",
    slug: "why-raelina-ended-up-at-the-duke's-mansion",
    sub_ep: "12",
    dub_ep: "12",
    total_ep: "12",
    categories: ["2023", "sub", "dub", "tv"],
    description:
      "When Park Eunha dies in modern-day Korea, she awakens in the body of Raeliana McMillan, the eldest daughter of a nouveaux riche baron. However, this is no ordinary world; it's the exact same one as a novel she once read. Beloved by her family, it would seem as though she is in a fairy tale. But Raeliana is far from the main character—she is a mere plot device, whose murder at the hands of her fiancé instigates the entire story.Raeliana has no intention to accept her fate quietly. She sets her eyes on someone in a position of great power—the vieux riche male protagonist Duke Noah Volstaire Wynknight—aiming to completely change the original story. Using her knowledge of future events, Raeliana offers information to Noah on the condition that he acts as her fake fiancé, but the Duke's two-faced nature throws a wrench in her plans!",
    thumbnail: require("../assets/images/raelina_full.webp"),
  },
  {
    id: 4,
    title:
      "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too",
    slug: "i-got-a-cheat-skill-in-another-world",
    sub_ep: "13",
    dub_ep: "10",
    total_ep: "13",
    categories: ["2023", "sub", "dub", "tv"],
    description:
      "A chance to come back! A mysterious door stands open, inviting a boy who's been brutally bullied all his life to take a courageous step forward into the unknown. On the other side, he finds a hoard of priceless artifacts and a world as filled with magic as it is with monsters. The most shocking revelation, however, is that he can bring whatever he wants back with him when he returns to Earth. It won't be long before this double life changes him forever...",
    thumbnail: require("../assets/images/cheat_skill/cheat-skill-anime.webp"),
  },
  {
    id: 5,
    title: "One Piece",
    slug: "one-piece",
    sub_ep: "1066",
    dub_ep: "964",
    total_ep: "",
    categories: ["1999", "sub", "pg-13", "tv"],
    description: `Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey D. Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece.`,
    thumbnail: require("../assets/images/one_piece/one_piece_full.jpe"),
  },
  {
    id: 6,
    title: "In Another World With My Smartphone 2",
    slug: "in-another-world-with-my-smartphone-s2",
    sub_ep: "12",
    dub_ep: "11",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `Second season of Isekai wa Smartphone to Tomo ni.`,
    thumbnail: require("../assets/images/with_smartphone.jpe"),
  },
  {
    id: 7,
    title: "[Oshi No Ko]",
    slug: "oshi-no-ko",
    sub_ep: "11",
    dub_ep: "6",
    total_ep: "11",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `Sixteen-year-old Ai Hoshino is a talented and beautiful idol who is adored by her fans. She is the personification of a pure, young maiden. But all that glitters is not gold. Gorou Amemiya is a countryside gynecologist and a big fan of Ai. So when the pregnant idol shows up at his hospital, he is beyond bewildered. Gorou promises her a safe delivery. Little does he know, an encounter with a mysterious figure would result in his untimely death—or so he thought.Opening his eyes in the lap of his beloved idol, Gorou finds that he has been reborn as Aquamarine Hoshino—Ai's newborn son! With his world turned upside down, Gorou soon learns that the world of showbiz is paved with thorns, where talent does not always beget success. Will he manage to protect Ai's smile that he loves so much with the help of an eccentric and unexpected ally?`,
    thumbnail: require("../assets/images/oshi_no_ko/oshi_no_ko_full.jpg"),
  },
  {
    id: 8,
    title: "Too Cute Crisis",
    slug: "too-cute-crisis",
    sub_ep: "12",
    dub_ep: "",
    total_ep: "12",
    categories: ["2023", "sub", "tv"],
    description: `Liza Luna is an alien who wants to destroy Earth upon her first look. But the planet has a plethora of good things, and it would be a pity for her not to check it out. Thus, Earth is spared from destruction, and the alien starts to wander around places. Soon, Liza ends up in a cat cafe, where she will encounter creatures that are beyond her understanding.`,
    thumbnail: require("../assets/images/cute_crisis.jpg"),
  },
  {
    id: 9,
    title: "Rokudo's Bad Girls",
    slug: "rokudo's-bad-girls",
    sub_ep: "12",
    dub_ep: "",
    total_ep: "12",
    categories: ["2023", "sub", "tv"],
    description: `Tousuke Rokudou is a first-year attending Aomori High, a school full of delinquents. He is often bullied by his classmates due to his incompatibility with their behavior, the only exceptions being his two good friends who are also social outcasts. Frustrated at the way they are treated, the three wish they could stand up and claim the fun, peaceful school life of their dreams.However, Tousuke's life takes a drastic turn when he receives a package from his late grandfather containing their family heirloom, a scroll said to possess the power to save him from impending danger. Upon holding the scroll, a sudden glow emanates, leaving a strange mark on Tousuke's forehead.Thinking that he's received the means to free himself and his friends from their daily treatment, Tousuke is shocked to find out that its effects are far different than what he had imagined. Although his bullying continues, he realizes that the mark from the scroll acts as a charm, capturing the hearts of delinquent girls—in particular, Ranna Himawari, the strongest of them all.`,
    thumbnail: require("../assets/images/rokudo_full.jpe"),
  },
  {
    id: 10,
    title: "A Galaxy Next Door",
    slug: "a-galaxy-next-door",
    sub_ep: "12",
    dub_ep: "10",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `Ichirou Kuga has suddenly found himself taking on the responsibility of caring for his two younger siblings after their father's untimely death. To make ends meet, Ichirou rents out rooms in the apartment complex he inherited and works full-time as a shoujo manga artist. However, his manga sales are low, his assistants have recently left, and deadlines are fast approaching. As stress threatens to overtake Ichirou, salvation comes in the form of an extremely competent novice artist, Shiori Goshiki, who becomes his new assistant. With her skills, they are able to tide over the difficult situation, and things begin looking up. But in a bizarre accident, a supernatural experience unfolds between Ichirou and Shirou, which leads her to declare them engaged. With this seemingly innocuous action upending his life, Ichirou now has to manage his new and peculiar relationship with the mysterious girl, all the while following his own passion and fulfilling the duties that rest on his shoulders.`,
    thumbnail: require("../assets/images/a_galaxy_next_door.jpg"),
  },
  {
    id: 11,
    title: "Birdie Wing: Golf Girl's Story: 2nd Season",
    slug: "birdie-wing",
    sub_ep: "12",
    dub_ep: "",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "tv"],
    description: `Arriving in Japan, underground golfer Eve wants nothing more than to play a match against Aoi Amawashi, the "Innocent Tyrant" prodigy that caught her eye. However, the girls, wishing to finally settle the score on who is the better golfer, will have to wait until the conclusion of the All-Japan Girls' High School Gold Doubles Championship. Now competing together for the Raiou Girls' Academy's golf team, Eve and Aoi decide to work together to claim a win for their institution. For a chance at defeating their more challenging opponents, both girls must find a way to further develop their golfing styles. However, dangerous figureheads pull strings in the background, making this high school golf tournament much more serious than it appears. In addition, Eve's illusive past resurfaces, making matters between her and Aoi even more complicated than they already were.`,
    thumbnail: require("../assets/images/birdie_wing.jpe"),
  },
  {
    id: 11,
    title: "Hirogaru Sky! Precure",
    slug: "precure",
    sub_ep: "22",
    dub_ep: "",
    total_ep: "",
    categories: ["2023", "g", "sub", "tv"],
    description: `A major incident has occurred in the peaceful Sky Land!? The young Princess Elle has been kidnapped by the monsters of Underg Empire! A brave young girl, Sora, follows the princess through a mysterious hole. "TV"? "Cars"? Are those some kind of magic tools!?!? But there's no time to be surprised! She has to get the princess back to the castle...! Flying between two worlds! The adventure with the Pretty Cure begins now! It's hero time!`,
    thumbnail: require("../assets/images/pretty_cure/pretty_cure.jpeg"),
  },
  {
    id: 12,
    title: "Black Clover: Sword of the Wizard King",
    slug: "black-clover-movie",
    sub_ep: "1",
    dub_ep: "1",
    total_ep: "",
    categories: ["2023", "pg-13", "sub", "dub", "movie"],
    description: `As a lionhearted boy who can’t wield magic strives for the title of Wizard King, four banished Wizard Kings of yore return to crush the Clover Kingdom.`,
    thumbnail: require("../assets/images/black_clover/black_clover_movie.jpg"),
  },
  {
    id: 13,
    title: "Bleach",
    slug: "bleach",
    sub_ep: "366",
    dub_ep: "366",
    total_ep: "366",
    japanese: "BLEACH - ブリーチ -",
    aired: "Oct 5, 2004 to Mar 27, 2012",
    premiered: "fall 2004",
    duration: "24min",
    status: "finished airing",
    mal_score: "7.8",
    genres: [
      "action",
      "adventure",
      "supernatural",
      "comedy",
      "shounen",
      "super power",
    ],
    studio: "studio pierrot",
    seasons: [
      "bleach: the series (2004)",
      "bleach movie 1",
      "bleach movie 2",
      "bleach movie 3",
      "bleach movie 4",
      "bleach: tybw",
      "bleach: tybw-the-separation",
    ],
    categories: ["2004", "pg-13", "sub", "dub", "tv"],
    description: `Ichigo Kurosaki is an ordinary high schooler—until his family is attacked by a Hollow, a corrupt spirit that seeks to devour human souls. It is then that he meets a Soul Reaper named Rukia Kuchiki, who gets injured while protecting Ichigo's family from the assailant. To save his family, Ichigo accepts Rukia's offer of taking her powers and becomes a Soul Reaper as a result. However, as Rukia is unable to regain her powers, Ichigo is given the daunting task of hunting down the Hollows that plague their town. However, he is not alone in his fight, as he is later joined by his friends—classmates Orihime Inoue, Yasutora Sado, and Uryuu Ishida—who each have their own unique abilities. As Ichigo and his comrades get used to their new duties and support each other on and off the battlefield, the young Soul Reaper soon learns that the Hollows are not the only real threat to the human world.`,
    thumbnail: require("../assets/images/bleach/bleach.jpeg"),
  },
  {
    id: 13,
    title: "Bleach: Thousand-Year Blood War Arc",
    slug: "bleach-tybw",
    sub_ep: "13",
    dub_ep: "13",
    total_ep: "13",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `Substitute Soul Reaper Ichigo Kurosaki spends his days fighting against Hollows, dangerous evil spirits that threaten Karakura Town. Ichigo carries out his quest with his closest allies: Orihime Inoue, his childhood friend with a talent for healing; Yasutora Sado, his high school classmate with superhuman strength; and Uryuu Ishida, Ichigo's Quincy rival. Ichigo's vigilante routine is disrupted by the sudden appearance of Asguiaro Ebern, a dangerous Arrancar who heralds the return of Yhwach, an ancient Quincy king. Yhwach seeks to reignite the historic blood feud between Soul Reaper and Quincy, and he sets his sights on erasing both the human world and the Soul Society for good. Yhwach launches a two-pronged invasion into both the Soul Society and Hueco Mundo, the home of Hollows and Arrancar. In retaliation, Ichigo and his friends must fight alongside old allies and enemies alike to end Yhwach's campaign of carnage before the world itself comes to an end.`,
    thumbnail: require("../assets/images/bleach/bleach_tybw.jpg"),
  },
  {
    id: 14,
    title: "Cardcaptor Sakura",
    slug: "cardcaptor-sakura",
    sub_ep: "70",
    dub_ep: "70",
    total_ep: "70",
    categories: ["1998", "pg", "sub", "dub", "tv"],
    description: `Sakura Kinomoto is your garden-variety ten-year-old fourth grader, until one day, she stumbles upon a mysterious book containing a set of cards. Unfortunately, she has little time to divine what the cards mean because she accidentally stirs up a magical gust of wind and unintentionally scatters the cards all over the world. Suddenly awakened from the book, the Beast of the Seal, Keroberos (nicknamed Kero-chan), tells Sakura that she has released the mystical Clow Cards created by the sorcerer Clow Reed. The Cards are no ordinary playthings. Each of them possesses incredible powers, and because they like acting independently, Clow sealed all the Cards within a book. Now that the Cards are set free, they pose a grave danger upon the world, and it is up to Sakura to prevent the Cards from causing a catastrophe! Appointing Sakura the title of "the Cardcaptor" and granting her the Sealed Key, Keroberos tasks her with finding and recapturing all the Cards. Alongside her best friend Tomoyo Daidouji, and with Kero-chan's guidance, Sakura must learn to balance her new secret duty with the everyday troubles of a young girl involving love, family, and school, all while she takes flight on her magical adventures as Sakura the Cardcaptor.`,
    thumbnail: require("../assets/images/cardcapter_sakura.jpeg"),
  },
  {
    id: 15,
    title: "Case Closed",
    slug: "case-closed",
    sub_ep: "1088",
    dub_ep: "123",
    total_ep: "",
    categories: ["1996", "pg-13", "sub", "dub", "tv"],
    description: `Shinichi Kudou, a high school student of astounding talent in detective work, is well known for having solved several challenging cases. One day, when Shinichi spots two suspicious men and decides to follow them, he inadvertently becomes witness to a disturbing illegal activity. Unfortunately, he is caught in the act, so the men dose him with an experimental drug formulated by their criminal organization, leaving him to his death. However, to his own astonishment, Shinichi lives to see another day, but now in the body of a seven-year-old child.`,
    thumbnail: require("../assets/images/case_closed/case_closed.jpe"),
  },
  {
    id: 15,
    title: "Chainsaw Man",
    slug: "chainsaw-man",
    sub_ep: "12",
    dub_ep: "12",
    total_ep: "12",
    categories: ["2022", "r", "sub", "dub", "tv"],
    description: `Denji is robbed of a normal teenage life, left with nothing but his deadbeat father's overwhelming debt. His only companion is his pet, the chainsaw devil Pochita, with whom he slays devils for money that inevitably ends up in the yakuza's pockets. All Denji can do is dream of a good, simple life: one with delicious food and a beautiful girlfriend by his side. But an act of greedy betrayal by the yakuza leads to Denji's brutal, untimely death, crushing all hope of him ever achieving happiness. Remarkably, an old contract allows Pochita to merge with the deceased Denji and bestow devil powers on him, changing him into a hybrid able to transform his body parts into chainsaws. Because Denji's new abilities pose a significant risk to society, the Public Safety Bureau's elite devil hunter Makima takes him in, letting him live as long as he obeys her command. Guided by the promise of a content life alongside an attractive woman, Denji devotes everything and fights with all his might to make his naive dreams a reality.`,
    thumbnail: require("../assets/images/chainsaw_man.jpeg"),
  },
  {
    id: 16,
    title:
      "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too",
    slug: "cheat-skill",
    sub_ep: "13",
    dub_ep: "10",
    total_ep: "13",
    categories: ["2022", "pg-13", "sub", "dub", "tv"],
    description: `All his life, Yuuya Tenjou has been the subject of resentment and contempt from everyone around him, even from his parents. To make matters worse, his grandfather—the only person who ever showed him affection—suddenly dies, leaving Yuuya truly alone. Despite facing many adversities, Yuuya does what he can to offer kindness to those who need it—but even the most good-natured people can only tolerate so much abuse. Just when he reaches his breaking point, a flicker of hope appears in the form of a hidden door in his bathroom. This door provides two-way access to an abandoned house in another world, where he instantly gains game-like stats and skills. Moreover, the house once belonged to a sage, which gives Yuuya access to remarkable weapons, equipment, and crops with extraordinary effects. With these newfound blessings, the once-undesirable Yuuya may just reach his true potential and become unstoppable. `,
    thumbnail: require("../assets/images/cheat_skill/cheat_skill.jpg"),
  },
  {
    id: 17,
    title: "Cowboy Bepop",
    slug: "cowboy-bepop",
    sub_ep: "26",
    dub_ep: "26",
    total_ep: "26",
    categories: ["1998", "r", "sub", "dub", "tv"],
    description: `In the year 2071, humanity has colonized several of the planets and moons of the solar system leaving the now uninhabitable surface of planet Earth behind. The Inter Solar System Police attempts to keep peace in the galaxy, aided in part by outlaw bounty hunters, referred to as "Cowboys." The ragtag team aboard the spaceship Bebop are two such individuals. Mellow and carefree Spike Spiegel is balanced by his boisterous, pragmatic partner Jet Black as the pair makes a living chasing bounties and collecting rewards. Thrown off course by the addition of new members that they meet in their travels—Ein, a genetically engineered, highly intelligent Welsh Corgi; femme fatale Faye Valentine, an enigmatic trickster with memory loss; and the strange computer whiz kid Edward Wong—the crew embarks on thrilling adventures that unravel each member's dark and mysterious past little by little. Well-balanced with high density action and light-hearted comedy, Cowboy Bebop is a space Western classic and an homage to the smooth and improvised music it is named after. `,
    thumbnail: require("../assets/images/cowboy_bepop/cowboy_bepop.jpg"),
  },
  {
    id: 18,
    title: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc",
    slug: "kimetsu-no-yaiba-s3",
    sub_ep: "11",
    dub_ep: "5",
    total_ep: "11",
    categories: ["2023", "r", "sub", "dub", "tv"],
    description: `Swordsmith Village Arc of Kimetsu no Yaiba.`,
    thumbnail: require("../assets/images/demon_slayer/demon_slayer_s3.jpe"),
  },
  {
    id: 19,
    title: "Dragon Ball",
    slug: "dragon-ball",
    sub_ep: "153",
    dub_ep: "153",
    total_ep: "153",
    categories: ["1986", "pg-13", "sub", "dub", "tv"],
    description: `SON-Goku is a young boy who lives in the woods all alone—that is, until a girl named Bulma runs into him in her search for a set of magical objects called the "Dragon Balls." Since the artifacts are said to grant one wish to whoever collects all seven, Bulma hopes to gather them and wish for a perfect boyfriend. Goku happens to be in possession of a dragon ball, but unfortunately for Bulma, he refuses to part ways with it, so she makes him a deal: he can tag along on her journey if he lets her borrow the dragon ball's power. With that, the two set off on the journey of a lifetime. They don't go on the journey alone. On the way, they meet the old Muten-Roshi and wannabe disciple Kuririn, with whom Goku trains to become a stronger martial artist for the upcoming World Martial Arts Tournament. However, it's not all fun and games; the ability to make any wish come true is a powerful one, and there are others who would do much worse than just wishing for a boyfriend. To stop those who would try to abuse the legendary power, they train to become stronger fighters, using their newfound strength to help the people around them along the way.`,
    thumbnail: require("../assets/images/dragon_ball/dragon_ball.jpeg"),
  },
  {
    id: 20,
    title: "Dragon Ball Z",
    slug: "dragon-ball-z",
    sub_ep: "291",
    dub_ep: "291",
    total_ep: "291",
    categories: ["1989", "pg-13", "sub", "dub", "tv"],
    description: `Five years after winning the World Martial Arts tournament, SON-Goku is now living a peaceful life with his wife and son. This changes, however, with the arrival of a mysterious enemy named Raditz who presents himself as Goku's long-lost brother. He reveals that Goku is a warrior from the once powerful but now virtually extinct Saiyan race, whose homeworld was completely annihilated. When he was sent to Earth as a baby, Goku's sole purpose was to conquer and destroy the planet; but after suffering amnesia from a head injury, his violent and savage nature changed, and instead was raised as a kind and well-mannered boy, now fighting to protect others. With his failed attempt at forcibly recruiting Goku as an ally, Raditz warns Goku's friends of a new threat that's rapidly approaching Earth—one that could plunge Earth into an intergalactic conflict and cause the heavens themselves to shake. A war will be fought over the seven mystical dragon balls, and only the strongest will survive in Dragon Ball Z.`,
    thumbnail: require("../assets/images/dragon_ball/dragon_ball_z.jpg"),
  },
  {
    id: 21,
    title: "Dragon Ball Super",
    slug: "dragon-ball-super",
    sub_ep: "131",
    dub_ep: "131",
    total_ep: "131",
    categories: ["2015", "pg-13", "sub", "dub", "tv"],
    description: `Seven years after the events of Dragon Ball Z, Earth is at peace, and its people live free from any dangers lurking in the universe. However, this peace is short-lived; a sleeping evil awakens in the dark reaches of the galaxy: Beerus, the ruthless God of Destruction. Disturbed by a prophecy that he will be defeated by a "Super Saiyan God," Beerus and his angelic attendant Whis start searching the universe for this mysterious being. Before long, they reach Earth where they encounter SON-Goku, one of the planet's mightiest warriors, and his similarly powerful friends.`,
    thumbnail: require("../assets/images/dragon_ball/dragon_ball_super.jpg"),
  },
  {
    id: 22,
    title: "Dr. Stone New World",
    slug: "dr-stone-new-world",
    sub_ep: "11",
    dub_ep: "11",
    total_ep: "11",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `With the ambitious Ryuusui Nanami on board, Senkuu Ishigami and his team are almost ready to sail the seas and reach the other side of the world—where the bizarre green light that petrified humanity originated. Thanks to the revival of a skillful chef, enough food is being prepared for the entire crew, and the incredible reinvention of the GPS promises to ensure safety on the open sea. Preparations for the upcoming journey progress swimmingly until Senkuu receives an eerie message from a mysterious source. More driven than ever, the scientist sets out to explore the new world and discover what it can offer for his scientific cause. Though the uncharted territories may hide unkind surprises, Senkuu, with a little help from science, is ready to take on any challenge.`,
    thumbnail: require("../assets/images/dr.stone/dr_stone.jpeg"),
  },
  {
    id: 23,
    title: "Edens Zero 2nd Season",
    slug: "eden's-zero-s2",
    sub_ep: "13",
    dub_ep: "0",
    total_ep: "",
    categories: ["2023", "pg-13", "sub", "tv"],
    description: `Now in possession of the Edens Zero, Shiki Granbell has gathered the Four Shining Stars. With the help of his new friends, Shiki will be able to breach Dragonfall—the border of the Sakura Cosmos swarming with mechanical dragons. Once that is achieved, he can continue his quest to find the goddess Mother. Before the Edens Zero crew can advance their journey, they notice a mysterious warship following them. Upon learning that the ship—the Belial Gore—belongs to Drakken Joe, Shiki and his crew attempt to infiltrate it, intent on figuring out why the Dark Alchemist is after them. In the process, the Edens Zero is taken hostage by Drakken's subordinates. Though they are in a tight situation, Shiki refuses to back down. Working together with his friends, Shiki will have to take down the Dark Alchemist if he hopes to make it out of the Belial Gore alive.`,
    thumbnail: require("../assets/images/edens_zero/edens_zero_s2.jpg"),
  },
  {
    id: 24,
    title: "Fate/stay night: Unlimited Blade Works",
    slug: "fate-stay-night",
    sub_ep: "12",
    dub_ep: "12",
    total_ep: "12",
    categories: ["2014", "r", "sub", "dub", "tv"],
    description: `The Holy Grail War is a battle royale among seven magi who serve as Masters. Masters, through the use of the command seals they are given when they enter the war, command Heroic Spirits known as Servants to fight for them in battle. In the Fifth Holy Grail War, Rin Toosaka is among the magi entering the competition. With her Servant, Archer, she hopes to obtain the ultimate prize—the Holy Grail, a magical artifact capable of granting its wielder any wish. One of Rin's classmates, Emiya Shirou, accidentally enters the competition and ends up commanding a Servant of his own known as Saber. As they find themselves facing mutual enemies, Rin and Shirou decide to form a temporary alliance as they challenge their opponents in the Holy Grail War.`,
    thumbnail: require("../assets/images/fate_series/fate_stay_night.jpg"),
  },
  {
    id: 25,
    title: "Fullmetal Alchemist: Brotherhood",
    slug: "fmab",
    sub_ep: "64",
    dub_ep: "64",
    total_ep: "64",
    categories: ["2009", "r", "sub", "dub", "tv"],
    description: `In order for something to be obtained, something of equal value must be lost." Alchemy is bound by this Law of Equivalent Exchange—something the young brothers Edward and Alphonse Elric only realize after attempting human transmutation: the one forbidden act of alchemy. They pay a terrible price for their transgression—Edward loses his left leg, Alphonse his physical body. It is only by the desperate sacrifice of Edward's right arm that he is able to affix Alphonse's soul to a suit of armor. Devastated and alone, it is the hope that they would both eventually return to their original bodies that gives Edward the inspiration to obtain metal limbs called "automail" and become a state alchemist, the Fullmetal Alchemist. Three years of searching later, the brothers seek the Philosopher's Stone, a mythical relic that allows an alchemist to overcome the Law of Equivalent Exchange. Even with military allies Colonel Roy Mustang, Lieutenant Riza Hawkeye, and Lieutenant Colonel Maes Hughes on their side, the brothers find themselves caught up in a nationwide conspiracy that leads them not only to the true nature of the elusive Philosopher's Stone, but their country's murky history as well. In between finding a serial killer and racing against time, Edward and Alphonse must ask themselves if what they are doing will make them human again... or take away their humanity.`,
    thumbnail: require("../assets/images/fullmetal_alchemist.jpg"),
  },
  {
    id: 26,
    title: "Great Teacher Onizuka",
    slug: "great-teacher-onizuka",
    sub_ep: "43",
    dub_ep: "43",
    total_ep: "43",
    categories: ["1999", "r", "sub", "dub", "tv"],
    description: `Twenty-two-year-old Eikichi Onizuka—ex-biker gang leader, conqueror of Shonan, and virgin—has a dream: to become the greatest high school teacher in all of Japan. This isn't because of a passion for teaching, but because he wants a loving teenage wife when he's old and gray. Still, for a perverted, greedy, and lazy delinquent, there is more to Onizuka than meets the eye. So when he lands a job as the homeroom teacher of the Class 3-4 at the prestigious Holy Forest Academy—despite suplexing the Vice Principal—all of his talents are put to the test, as this class is particularly infamous. Due to their utter contempt for all teachers, the class' students use psychological warfare to mentally break any new homeroom teacher they get, forcing them to quit and leave school. However, Onizuka isn't your average teacher, and he's ready for any challenge in his way. Bullying, suicide, and sexual harassment are just a few of the issues his students face daily. By tackling the roots of their problems, Onizuka supports them with his unpredictable and unconventional methods—even if it means jumping off a building to save a suicidal child. Thanks to his eccentric charm and fun-loving nature, Class 3-4 slowly learns just how enjoyable school can be when you're the pupils of the Great Teacher Onizuka.`,
    thumbnail: require("../assets/images/great_teacher_onizuka.jpg"),
  },
  {
    id: 27,
    title: "Hajime no Ippo",
    slug: "hajime-no-ippo",
    sub_ep: "75",
    dub_ep: "75",
    total_ep: "75",
    categories: ["2000", "pg-13", "sub", "dub", "tv"],
    description: `Makunouchi Ippo has been bullied his entire life. Constantly running errands and being beaten up by his classmates, Ippo has always dreamed of changing himself, but never has the passion to act upon it. One day, in the midst of yet another bullying, Ippo is saved by Takamura Mamoru, who happens to be a boxer. Ippo faints from his injuries and is brought to the Kamogawa boxing gym to recover. As he regains consciousness, he is awed and amazed at his new surroundings in the gym, though lacks confidence to attempt anything. Takamura places a photo of Ippo's classmate on a punching bag and forces him to punch it. It is only then that Ippo feels something stir inside him and eventually asks Takamura to train him in boxing. Thinking that Ippo does not have what it takes, Takamura gives him a task deemed impossible and gives him a one week time limit. With a sudden desire to get stronger, for himself and his hard working mother, Ippo trains relentlessly to accomplish the task within the time limit. Thus Ippo's journey to the top of the boxing world begins.`,
    thumbnail: require("../assets/images/hajime/hajime_no_ippo.jpg"),
  },
  {
    id: 28,
    title: "Hellsing",
    slug: "hellsing",
    sub_ep: "13",
    dub_ep: "13",
    total_ep: "13",
    categories: ["2001", "r", "sub", "dub", "tv"],
    description: `Hellsing, an organization specializing in dealing with supernatural threats, is called in to eliminate a vampire that is turning the villagers of Cheddar into ghouls. To put an end to this, the leader of the organization, Sir Integra Fairbrook Wingates Hellsing, dispatches her most formidable asset: a powerful vampire known as Alucard. Armed with only a single handgun, Alucard wreaks havoc on the monsters plaguing Cheddar. However, a young police officer, Seras Victoria, gets caught up in the chaos and becomes mortally wounded as a result. Taking pity on the girl, Alucard gives her a choice: die as a human or live on as a vampire. Seras accepts his offer and begins a new life as a member of Hellsing. Though it was her decision, Seras struggles with the fact that she is no longer human. Nevertheless, she must embrace being a creature of the night soon if she wants to survive on the front lines in the fight between humans and the supernatural.`,
    thumbnail: require("../assets/images/hellsing/hellsing.jpg"),
  },
  {
    id: 28,
    title: "Hell's Paradise",
    slug: "hell's-paradise",
    sub_ep: "12",
    dub_ep: "10",
    total_ep: "13",
    categories: ["2023", "r", "sub", "dub", "tv"],
    description: `Gabimaru the Hollow, a ninja of Iwagakure Village known for being cold and emotionless, was set up by his fellow ninja and is now on death row. Tired of killing and betrayal, he wants to die. However, no method of execution works on him because as much as the seemingly apathetic Gabimaru refuses to admit it, he does have a reason to live. He wants to return to his wife, who was the reason why he softened up and failed to be an effective assassin. Thus, he refuses to die. Asaemon the Decapitator, a famous executioner, sees this and has a proposal for the ninja. He wants Gabimaru to join an expedition to an island south of Japan in search of the elixir of life in exchange for a full pardon by the Shogunate. However, this island isn't a normal island: it's believed to be Paradise. However the island is full of mysteries, and the exploring team—consisting of those marked for death—might not be fully prepared to handle them.`,
    thumbnail: require("../assets/images/hell's_paradise.jpg"),
  },
  {
    id: 29,
    title: "The Legendary Hero Is Dead!",
    slug: "hero-is-dead",
    sub_ep: "12",
    dub_ep: "11",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `Far to the north of the world lies Hell's Gate, a portal formerly used by the Demon Lord to invade the human realm. Thanks to the legendary hero Shion Bladearts, wielder of Excalibur, and his loyal band of companions, the Gate was sealed off and the demonic threat was vanquished. Unfortunately, the seal was incomplete and has begun to weaken, allowing the demons to once again begin their attack. Worried about the safety of his village, selfish and perverted farmer Touka Scott dig pitfalls to defend against the demons. But fear not, for Shion is on his way to reseal Hell's Gate and save humanity! Or at least he was, because the legendary hero is dead, having fallen into one of the pitfalls Touka dug. Luckily, dealing with the dead is the specialty of necromancer Anri Haynesworth. While she can't revive him, Anri can at least salvage their quest by forcing Touka's soul into Shion's rotting body and dragging him along to Hell's Gate in Shion's place. Not wanting to be left behind, Touka's childhood friend Yuna Yunis tags along. Together, the three of them set out as what just might be the most unsuitable party to ever try to save the world!`,
    thumbnail: require("../assets/images/hero_is_dead.jpg"),
  },
  {
    id: 30,
    title: "KamiKatsu: Working for God in a Godless World",
    slug: "kamikatsu-godelss-world",
    sub_ep: "11",
    dub_ep: "10",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `Under the belief that the omnipotent god Mitama will come to save him, Yukito Urabe participates in a ritual to become the new leader of his father's cult. But when the boy drowns during the ritual, he wishes to be reborn in a world without gods or religion. Reawakening in a completely different world devoid of spirituality. He meets a deviant girl named Aruaru, who introduces him to her village. However, his idyllic image of this world's society is short-lived when he witnesses a public group suicide and learns of the country's end-of-life system: at any moment, the government may order any citizen to die. Aruaru and her sister are forcibly taken for execution soon after, prompting Yukito to rush to their rescue—but to no avail. In a moment of desperation, Yukito recalls his father's teachings and utters a prayer for Mitama to save them. Seemingly answering his call, a little girl descends from the sky and annihilates everyone who harmed Yukito and his friends. To Yukito's surprise, the girl introduces herself as Mitama.`,
    thumbnail: require("../assets/images/kamikatsu/kamikatsu_1.jpe"),
  },
  {
    id: 31,
    title: "Magical Girl Magical Destroyers",
    slug: "magical-destroyer",
    sub_ep: "12",
    dub_ep: "",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "tv"],
    description: `In 2008, the Japanese government began hunting people who identify as otaku in an effort to protect the country's culture. In just one week, the enforcement agency known as the SSC captured almost every otaku by force and confiscated their memorabilia. One passionate man calling himself Otaku Hero refuses to allow this agency to do as they please: he raises a resistance army made up of other displaced geeks who band together to help defend their culture. Three years later, the fires of rebellion wane as all hope seems lost for otakus. Spurred on by his ally—the magical girl Anarchy—Otaku Hero commands the resistance in an effort to reunite Anarchy with the other two other magical girls: Blue and Pink. By combining the power of this trio, the resistance may be able to defeat the SSC and save otaku culture for everyone.`,
    thumbnail: require("../assets/images/magical_destroyer.jpeg"),
  },
  {
    id: 32,
    title: "Mashle: Magic and Muscles",
    slug: "mashle",
    sub_ep: "11",
    dub_ep: "5",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "tv"],
    description: `To everyone else in his magic-dominated world, the young and powerless Mash Burnedead is a threat to the gene pool and must be purged. Living secretly in the forest, he spends every day training his body, building muscles strong enough to compete with magic itself! However, upon having his identity exposed and his peaceful life threatened, Mash begins his journey to becoming a "Divine Visionary," a role so powerful that society would have no choice but to accept his existence. And so, in order to maintain his peaceful life, the magicless Mash enrolls in the prestigious Easton Magic Academy, competing against the children of some of the most powerful and elite in the realm. Lacking the very skill needed to survive at Easton, magic, Mash appears to already be at a disadvantage to his fellow classmates. In order to achieve his goals, Mash will have to fight his way through every trial using his fists alone, overcoming magic with muscles, all for the illustrious title of Divine Visionary! `,
    thumbnail: require("../assets/images/mashle.jpg"),
  },
  {
    id: 33,
    title: "My Hero Academia Season 6",
    slug: "mha-s6",
    sub_ep: "23",
    dub_ep: "23",
    total_ep: "23",
    categories: ["2022", "pg-13", "sub", "dub", "tv"],
    description: `With Tomura Shigaraki at its helm, the former Liberation Army is now known as the Paranormal Liberation Front. This organized criminal group poses an immense threat to the Hero Association, not only because of its sheer size and strength, but also the overpowering quirks of Jin "Twice" Bubaigawara and Gigantomachia. As new intel from the covert hero Keigo "Hawks" Takami confirms that Shigaraki is nowhere to be seen, the Hero Association decides to strike the enemy headquarters with a surprise attack using the entirety of its assets—and the UA students find themselves on the battlefield once again. As the fight rages on, the unsuspecting villains must regroup and push back, but the brave heroes are determined to eradicate every last one of them.`,
    thumbnail: require("../assets/images/mha/mha_s6.jpeg"),
  },
  {
    id: 34,
    title: "My One-Hit Kill Sister",
    slug: "my-one-hit-kill-sister",
    sub_ep: "12",
    dub_ep: "",
    total_ep: "12",
    categories: ["2022", "pg-13", "sub", "tv"],
    description: `While saving a child from harm, otaku Asahi Ikusaba is transported to another world and believes he has reincarnated with cheat skills similar to those of the characters from his favorite games and novels. Unfortunately, reality strikes when an encounter with a powerful monster shows that he is still nothing more than an average person. In this moment of extreme danger, Asahi instinctively calls out to his overly doting sister, Maya, who appears out of nowhere, possessing the overpowered abilities he thought he had. Maya is ecstatic to see her brother again and resolves to use her newfound powers to protect Asahi no matter what. Together, the close-knit siblings attempt to find a way back home while enjoying their new lives. However, it soon becomes clear that their arrival in this world may have had a purpose. With the Demon King's overwhelmingly powerful army approaching, no one but Maya seems to be able to stand in its way.`,
    thumbnail: require("../assets/images/my_one_hit_kill_sister.jpg"),
  },
  {
    id: 35,
    title: "Naruto",
    slug: "naruto",
    sub_ep: "220",
    dub_ep: "220",
    total_ep: "220",
    categories: ["2002", "pg-13", "sub", "dub", "tv"],
    description: `Moments prior to Naruto Uzumaki's birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the Hidden Leaf Village, and wreaked havoc. In order to put an end to the Kyuubi's rampage, the leader of the village, the Fourth Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. Now, Naruto is a hyperactive and knuckle-headed ninja still living in Konohagakure. Shunned because of the Kyuubi inside him, Naruto struggles to find his place in the village, while his burning desire to become the Hokage of Konohagakure leads him not only to some great new friends, but also some deadly foes.`,
    thumbnail: require("../assets/images/naruto/naruto.jpg"),
  },
  {
    id: 36,
    title: "One Piece",
    slug: "one-piece-trending",
    sub_ep: "1066",
    dub_ep: "964",
    total_ep: "",
    categories: ["1999", "sub", "pg-13", "tv"],
    description: `Gol D. Roger was known as the "Pirate King," the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey D. Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece.`,
    thumbnail: require("../assets/images/one_piece/one_piece.jpeg"),
  },
  {
    id: 37,
    title: "Oshi no Ko",
    slug: "my-star",
    sub_ep: "11",
    dub_ep: "6",
    total_ep: "11",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `Sixteen-year-old Ai Hoshino is a talented and beautiful idol who is adored by her fans. She is the personification of a pure, young maiden. But all that glitters is not gold. Gorou Amemiya is a countryside gynecologist and a big fan of Ai. So when the pregnant idol shows up at his hospital, he is beyond bewildered. Gorou promises her a safe delivery. Little does he know, an encounter with a mysterious figure would result in his untimely death—or so he thought.Opening his eyes in the lap of his beloved idol, Gorou finds that he has been reborn as Aquamarine Hoshino—Ai's newborn son! With his world turned upside down, Gorou soon learns that the world of showbiz is paved with thorns, where talent does not always beget success. Will he manage to protect Ai's smile that he loves so much with the help of an eccentric and unexpected ally?`,
    thumbnail: require("../assets/images/oshi_no_ko/oshi_no_ko.jpg"),
  },
  {
    id: 38,
    title: "Blue Lock",
    slug: "blue-lock",
    sub_ep: "24",
    dub_ep: "24",
    total_ep: "24",
    categories: ["2022", "pg-13", "sub", "dub", "tv"],
    description: `Yoichi Isagi was mere moments away from scoring a goal that would have sent his high school soccer team to the nationals, but a split-second decision to pass the ball to his teammate cost him that reality. Bitter, confused, and disappointed, Isagi wonders if the outcome would have been different had he not made the pass. When the young striker returns home, an invitation from the Japan Football Union awaits him. Through an arbitrary and biased decision-making process, Isagi is one of three hundred U-18 strikers selected for a controversial project named Blue Lock. The project's ultimate goal is to turn one of the selected players into the star striker for the Japanese national team. To find the best participant, each diamond in the rough must compete against others through a series of solo and team competitions to rise to the top. Putting aside his ethical objections to the project, Isagi feels compelled to fight his way to the top, even if it means ruthlessly crushing the dreams of 299 aspiring young strikers.`,
    thumbnail: require("../assets/images/blue_lock.jpeg"),
  },
  {
    id: 39,
    title: "Tokyo Revengers: Christmas Showdown",
    slug: "tokyo-revengers-s2",
    sub_ep: "13",
    dub_ep: "13",
    total_ep: "13",
    categories: ["2023", "r", "sub", "dub", "tv"],
    description: `In spite of his best time-leaping efforts, Takemichi Hanagaki continuously fails to prevent the present-day death of Hinata Tachibana, his adolescent love. The adult Takemichi grapples with grief and the ramifications of the Tokyo Manji gang's criminal empire—an unintended product of his timeline meddling. Though the gang once operated under the idealistic Manjirou "Mikey" Sano, it has now been taken over by the malicious Tetta Kisaki and, as a result, has abandoned its original optimistic intent. Despite feeling hopeless, Takemichi travels to the past once again to investigate Black Dragon, a rival motorcycle gang whose actions ultimately lead to Hinata's demise. There, he meets the young Hakkai Shiba, a fellow gang member whose older brother, Taiju, tyrannically rules Black Dragon. When Taiju brutally beats Takemichi in a one-sided street brawl, Hakkai attempts to withdraw from Tokyo Manji in apology—an act that Takemichi must prevent to spare Hakkai a grim future. Through a shared tragedy, Takemichi bonds with Chifuyu Matsuno, establishing a close comradery both boys desperately need. With Chifuyu on his side, Takemichi works to unravel the fates of Black Dragon's members, fighting to create a happy future for his loved ones.`,
    thumbnail: require("../assets/images/tokyo_revengers/tokyo_revengers_s2.webp"),
  },
  {
    id: 40,
    title: "Ranking of Kings: The Treasure Chest of Courage",
    slug: "ranking-of-kings-s2",
    sub_ep: "10",
    dub_ep: "10",
    total_ep: "10",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `The people of the kingdom look down on the young Prince Bojji, who can neither hear nor speak. They call him "The Useless Prince" while jeering at his supposed foolishness. However, while Bojji may not be physically strong, he is certainly not weak of heart. When a chance encounter with a shadow creature should have left him traumatized, it instead makes him believe that he has found a friend amidst those who only choose to notice his shortcomings. He starts meeting with Kage, the shadow, regularly, to the point where even the otherwise abrasive creature begins to warm up to him. Kage and Bojji's unlikely friendship lays the budding foundations of the prince's journey, one where he intends to conquer his fears and insecurities. Despite the constant ridicule he faces, Bojji resolves to fulfill his desire of becoming the best king he can be.`,
    thumbnail: require("../assets/images/ranking_of_kings/ranking_of_kings_s2.jpeg"),
  },
  {
    id: 41,
    title: "Rurouni Kenshin",
    slug: "rurouni-kenshin",
    sub_ep: "94",
    dub_ep: "94",
    total_ep: "94",
    categories: ["1996", "pg-13", "sub", "dub", "tv"],
    description: `In the final years of the Bakumatsu era lived a legendary assassin known as Hitokiri Battousai. Feared as a merciless killer, he was unmatched throughout the country, but mysteriously disappeared at the peak of the Japanese Revolution. It has been ten peaceful years since then, but the very mention of Battousai still strikes terror into the hearts of war veterans. Unbeknownst to them, Battousai has abandoned his bloodstained lifestyle in an effort to repent for his sins, now living as Kenshin Himura, a wandering swordsman with a cheerful attitude and a strong will. Vowing never to kill again, Kenshin dedicates himself to protecting the weak. One day, he stumbles across Kaoru Kamiya at her kendo dojo, which is being threatened by an impostor claiming to be Battousai. After receiving help from Kenshin, Kaoru allows him to stay at the dojo, and so the former assassin temporarily ceases his travels. Rurouni Kenshin: Meiji Kenkaku Romantan tells the story of Kenshin as he strives to save those in need of saving. However, as enemies from both past and present begin to emerge, will the reformed killer be able to uphold his new ideals?`,
    thumbnail: require("../assets/images/rurouni_kenshin/rurouni_kenshin.jpg"),
  },
  {
    id: 42,
    title: "Samurai Champloo",
    slug: "samurai-champloo",
    sub_ep: "26",
    dub_ep: "26",
    total_ep: "26",
    categories: ["2004", "r", "sub", "dub", "tv"],
    description: `Fuu Kasumi is a young and clumsy waitress who spends her days peacefully working in a small teahouse. That is, until she accidentally spills a drink all over one of her customers! With a group of samurai now incessantly harassing her, Fuu desperately calls upon another samurai in the shop, Mugen, who quickly defeats them with his wild fighting technique, utilizing movements reminiscent to that of breakdancing. Unfortunately, Mugen decides to pick a fight with the unwilling ronin Jin, who wields a more precise and traditional style of swordfighting, and the latter proves to be a formidable opponent. The only problem is, they end up destroying the entire shop as well as accidentally killing the local magistrate's son. For their crime, the two samurai are captured and set to be executed. However, they are rescued by Fuu, who hires the duo as her bodyguards. Though she no longer has a place to return to, the former waitress wishes to find a certain samurai who smells of sunflowers and enlists the help of the now exonerated pair to do so. Despite initially disapproving of this idea, the two eventually agree to assist the girl in her quest; thus, the trio embark upon an adventure to find this mysterious warrior—that is, if Fuu can keep Mugen and Jin from killing each other. Set in an alternate Edo Period of Japan, Samurai Champloo follows the journey of these three eccentric individuals in an epic quest full of action, comedy, and dynamic sword fighting, all set to the beat of a unique hip-hop infused soundtrack.`,
    thumbnail: require("../assets/images/samurai_champloo/samurai_champloo.jpg"),
  },
  {
    id: 43,
    title: "Slam Dunk",
    slug: "slam-dunk",
    sub_ep: "101",
    dub_ep: "85",
    total_ep: "101",
    categories: ["1993", "pg-13", "sub", "dub", "tv"],
    description: `Hanamichi Sakuragi, infamous for his temper, massive height, and fire-red hair, enrolls in Shohoku High, hoping to finally get a girlfriend and break his record of being rejected 50 consecutive times in middle school. His notoriety precedes him, however, leading to him being avoided by most students. Soon, after certain events, Hanamichi is left with two unwavering thoughts: "I hate basketball," and "I desperately need a girlfriend." One day, a girl named Haruko Akagi approaches him without any knowledge of his troublemaking ways and asks him if he likes basketball. Hanamichi immediately falls head over heels in love with her, blurting out a fervent affirmative. She then leads him to the gymnasium, where she asks him if he can do a slam dunk. In an attempt to impress Haruko, he makes the leap, but overshoots, instead slamming his head straight into the blackboard. When Haruko informs the basketball team's captain of Hanamichi's near-inhuman physical capabilities, he slowly finds himself drawn into the camaraderie and competition of the sport he had previously held resentment for.`,
    thumbnail: require("../assets/images/slam_dunk/slam_dunk.jpg"),
  },
  {
    id: 44,
    title: "Spice and Wolf",
    slug: "spice-and-wolf",
    sub_ep: "13",
    dub_ep: "13",
    total_ep: "13",
    categories: ["2008", "pg-13", "sub", "dub", "tv"],
    description: `Holo is a powerful wolf deity who is celebrated and revered in the small town of Pasloe for blessing the annual harvest. Yet as years go by and the villagers become more self-sufficient, Holo, who stylizes herself as the "Wise Wolf of Yoitsu," has been reduced to a mere folk tale. When a traveling merchant named Kraft Lawrence stops at Pasloe, Holo offers to become his business partner if he eventually takes her to her northern home of Yoitsu. The savvy trader recognizes Holo's unusual ability to evaluate a person's character and accepts her proposition. Now in the possession of both sharp business skills and a charismatic negotiator, Lawrence inches closer to his goal of opening his own shop. However, as Lawrence travels the countryside with Holo in search of economic opportunities, he begins to realize that his aspirations are slowly morphing into something unexpected. Based on the popular light novel of the same name, Ookami to Koushinryou, also known as Spice and Wolf, fuses the two polar genres of economics and romance to create an enthralling story abundant with elaborate schemes, sharp humor, and witty dialogue. Ookami to Koushinryou is more than just a story of bartering; it turns into a journey of searching for a lost identity in an ever-changing world.`,
    thumbnail: require("../assets/images/spice_and_wolf.jpg"),
  },
  {
    id: 45,
    title: "Summoned to Another World for a Second Time",
    slug: "summoned-to-another-world",
    sub_ep: "12",
    dub_ep: "",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "tv"],
    description: `There was once a man who was summoned to another world, and saved it. Of course, he became too popular there, and turned into an isekai-normie. However, that man fell into a "trap" and was forcibly returned to his original world. Moreover, he had to start over as a baby! This is the story of the way-too-fantastic ex-hero who lived as a gloomy high-schooler, as he gets summoned once again to that same other world in a very unexpected development!`,
    thumbnail: require("../assets/images/summoned_to_another_world.jpg"),
  },
  {
    id: 46,
    title: "The Ancient Magus' Bride Season 2",
    slug: "the-ancient-magus'-bride-s2",
    sub_ep: "12",
    dub_ep: "11",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "dub", "tv"],
    description: `Apprentice mage Chise Hatori is invited to enroll at the College, a prestigious learning institution for sorcerers, to examine and look for a way to remove the curses she bears. Despite her groom Elias Ainsworth's reluctance, Chise accepts the proposal, as she believes attending the school might help her minimize her self-sacrificing tendencies. From the get-go, Chise grabs the attention of her classmates and professors alike, who have never seen a mage in action before. However, there is a sinister plot brewing behind the College's back, and the young mage will have to determine who is friend or foe in order to put a stop to it.`,
    thumbnail: require("../assets/images/magus_bride/the_anicient_magus.jpe"),
  },
  {
    id: 47,
    title: "The Café Terrace and Its Goddesses",
    slug: "the-café-terrace-and-its-goddesses",
    sub_ep: "12",
    dub_ep: "",
    total_ep: "12",
    categories: ["2023", "r", "sub", "tv"],
    description: `When Hayato's grandmother passed, he planned to sell her rundown café on the shore—not realizing that it was also home to five young women who call themselves her family?! Their desperation to keep the café open convinces Hayato to give it a shot...but even their best intentions might not be enough to make it work! And can he even work with these five unruly women? No matter what, he's got his work cut out for him!`,
    thumbnail: require("../assets/images/the_cafe_terrace.jpe"),
  },
  {
    id: 48,
    title: "The Dangers in My Heart",
    slug: "the-dangers-in-my-heart",
    sub_ep: "12",
    dub_ep: "",
    total_ep: "12",
    categories: ["2023", "pg-13", "sub", "tv"],
    description: `Kyoutarou Ichikawa may look like a shy and reserved middle school student, but deep within his heart is a bloodthirsty killer. His ultimate desire is to see his classmate Anna Yamada's beautiful face writhing in pain before he ends her life. But this fantasy may never come to fruition, as Ichikawa starts to see an entirely different side to Yamada. Often seeking refuge in the library, Ichikawa frequently runs into Yamada. It is during these encounters that Ichikawa realizes his model classmate is actually an airhead who can never read the room. As they spend more time together, the boy cannot help but feel not only a sense of endearment toward the very girl he wishes to murder but also a desire to protect her at all costs. Is it possible that this sudden change in Ichikawa's perspective could lead to something more?`,
    thumbnail: require("../assets/images/the_dangers_in_my_heart.jpg"),
  },
  {
    id: 49,
    title: "Trigun",
    slug: "trigun",
    sub_ep: "26",
    dub_ep: "26",
    total_ep: "26",
    categories: ["1998", "pg-13", "sub", "dub", "tv"],
    description: `Vash the Stampede is the man with a $$60,000,000,000 bounty on his head. The reason: he's a merciless villain who lays waste to all those that oppose him and flattens entire cities for fun, garnering him the title "The Humanoid Typhoon." He leaves a trail of death and destruction wherever he goes, and anyone can count themselves dead if they so much as make eye contact—or so the rumors say. In actuality, Vash is a huge softie who claims to have never taken a life and avoids violence at all costs. With his crazy doughnut obsession and buffoonish attitude in tow, Vash traverses the wasteland of the planet Gunsmoke, all the while followed by two insurance agents, Meryl Stryfe and Milly Thompson, who attempt to minimize his impact on the public. But soon, their misadventures evolve into life-or-death situations as a group of legendary assassins are summoned to bring about suffering to the trio. Vash's agonizing past will be unraveled and his morality and principles pushed to the breaking point.`,
    thumbnail: require("../assets/images/trigun/trigun.jpg"),
  },
  {
    id: 50,
    title: "Utawarerumono: Mask of Truth",
    slug: "utawarerumono",
    sub_ep: "28",
    dub_ep: "25",
    total_ep: "28",
    categories: ["2022", "pg-13", "sub", "dub", "tv"],
    description: `After the events of Mask of Deception, the Yamato Empire is now ruled with an iron fist by a ruthless usurper who seeks to subjugate all before him. It's up to a couple of familiar faces to band together against the might of the Imperial army, and the fate of the world hangs in the balance as nations and generals must pick a side to fight with in this perilous civil war. Secrets will be revealed, friendships will be tested, and battles will be fought. Will peace and order be restored or will victory at any cost be the beginning of the end?`,
    thumbnail: require("../assets/images/utawarerumono.jpg"),
  },
  {
    id: 51,
    title: "Vinland Saga",
    slug: "vinland-saga",
    sub_ep: "24",
    dub_ep: "24",
    total_ep: "24",
    categories: ["2019", "r", "sub", "dub", "tv"],
    description: `Young Thorfinn grew up listening to the stories of old sailors that had traveled the ocean and reached the place of legend, Vinland. It's said to be warm and fertile, a place where there would be no need for fighting—not at all like the frozen village in Iceland where he was born, and certainly not like his current life as a mercenary. War is his home now. Though his father once told him, "You have no enemies, nobody does. There is nobody who it's okay to hurt," as he grew, Thorfinn knew that nothing was further from the truth. The war between England and the Danes grows worse with each passing year. Death has become commonplace, and the viking mercenaries are loving every moment of it. Allying with either side will cause a massive swing in the balance of power, and the vikings are happy to make names for themselves and take any spoils they earn along the way. Among the chaos, Thorfinn must take his revenge and kill Askeladd, the man who murdered his father. The only paradise for the vikings, it seems, is the era of war and death that rages on.`,
    thumbnail: require("../assets/images/vinland_saga/vinland_saga.jpg"),
  },
  {
    id: 52,
    title: "Vinland Saga: 2nd Season",
    slug: "vinland-saga-s2",
    sub_ep: "24",
    dub_ep: "23",
    total_ep: "24",
    categories: ["2023", "r", "sub", "dub", "tv"],
    description: `After his father's death and the destruction of his village at the hands of English raiders, Einar wishes for a peaceful life with his family on their newly rebuilt farms. However, fate has other plans: his village is invaded once again. Einar watches helplessly as the marauding Danes burn his lands and slaughter his family. The invaders capture Einar and take him back to Denmark as a slave. Einar clings to his mother's final words to survive. He is purchased by Ketil, a kind slave owner and landlord who promises that Einar can regain his freedom in return for working in the fields. Soon, Einar encounters his new partner in farm cultivation—Thorfinn, a dejected and melancholic slave. As Einar and Thorfinn work together toward their freedom, they are haunted by both sins of the past and the ploys of the present. Yet they carry on, grasping for a glimmer of hope, redemption, and peace in a world that is nothing but unjust and unforgiving. `,
    thumbnail: require("../assets/images/vinland_saga/vinland_saga_s2.jpg"),
  },
  {
    id: 53,
    title: "Loving Yamada at Lv999",
    slug: "loving-yamada-at-lv999",
    sub_ep: "13",
    dub_ep: "",
    total_ep: "13",
    categories: ["2023", "pg-13", "sub", "tv"],
    description: `After his father's death and the destruction of his village at the hands of English raiders, Einar wishes for a peaceful life with his family on their newly rebuilt farms. However, fate has other plans: his village is invaded once again. Einar watches helplessly as the marauding Danes burn his lands and slaughter his family. The invaders capture Einar and take him back to Denmark as a slave. Einar clings to his mother's final words to survive. He is purchased by Ketil, a kind slave owner and landlord who promises that Einar can regain his freedom in return for working in the fields. Soon, Einar encounters his new partner in farm cultivation—Thorfinn, a dejected and melancholic slave. As Einar and Thorfinn work together toward their freedom, they are haunted by both sins of the past and the ploys of the present. Yet they carry on, grasping for a glimmer of hope, redemption, and peace in a world that is nothing but unjust and unforgiving. `,
    thumbnail: require("../assets/images/yamada_kun.jpeg"),
  },
];

export const filterAnime = (slug) => anime.find((item) => item.slug === slug);

export const heroSlider = [
  filterAnime("demon-slayer-s3"),
  filterAnime("kamikatsu"),
  filterAnime("why-raelina-ended-up-at-the-duke's-mansion"),
  filterAnime("i-got-a-cheat-skill-in-another-world"),
  filterAnime("one-piece"),
  filterAnime("in-another-world-with-my-smartphone-s2"),
  filterAnime("oshi-no-ko"),
  filterAnime("rokudo's-bad-girls"),
];

export const trendingSlider = [
  filterAnime("one-piece-trending"),
  filterAnime("kimetsu-no-yaiba-s3"),
  filterAnime("my-star"),
  filterAnime("cheat-skill"),
  filterAnime("mashle"),
  filterAnime("hell's-paradise"),
  filterAnime("dr-stone-new-world"),
  filterAnime("blue-lock"),
  filterAnime("mha-s6"),
  filterAnime("tokyo-revengers-s2"),
];

export const latestUpdate = [
  filterAnime("one-piece-trending"),
  filterAnime("kimetsu-no-yaiba-s3"),
  filterAnime("hell's-paradise"),
  filterAnime("loving-yamada-at-lv999"),
  filterAnime("cheat-skill"),
  filterAnime("vinland-saga-s2"),
  filterAnime("too-cute-crisis"),
  filterAnime("a-galaxy-next-door"),
  filterAnime("birdie-wing"),
  filterAnime("eden's-zero-s2"),
  filterAnime("chainsaw-man"),
  filterAnime("ranking-of-kings-s2"),
  filterAnime("the-ancient-magus'-bride-s2"),
  filterAnime("hero-is-dead"),
  filterAnime("magical-destroyer"),
];

export const trendingShow = [
  filterAnime("one-piece-trending"),
  filterAnime("mashle"),
  filterAnime("bleach-tybw"),
  filterAnime("kimetsu-no-yaiba-s3"),
  filterAnime("cheat-skill"),
  filterAnime("my-star"),
  filterAnime("blue-lock"),
  filterAnime("a-galaxy-next-door"),
  filterAnime("summoned-to-another-world"),
  filterAnime("eden's-zero-s2"),
  filterAnime("the-café-terrace-and-its-goddesses"),
  filterAnime("utawarerumono"),
  filterAnime("the-ancient-magus'-bride-s2"),
  filterAnime("hero-is-dead"),
  filterAnime("magical-destroyer"),
];

export const popularShow = [
  filterAnime("naruto"),
  filterAnime("bleach"),
  filterAnime("trigun"),
  filterAnime("cowboy-bepop"),
  filterAnime("rurouni-kenshin"),
  filterAnime("fmab"),
  filterAnime("dragon-ball"),
  filterAnime("dragon-ball-z"),
  filterAnime("hajime-no-ippo"),
  filterAnime("hellsing"),
  filterAnime("fate-stay-night"),
  filterAnime("samurai-champloo"),
  filterAnime("cardcaptor-sakura"),
  filterAnime("great-teacher-onizuka"),
  filterAnime("slam-dunk"),
];
